from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Dict, List

from openpyxl.drawing.image import Image as XLImage
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

from ..quickchart_client import QuickChartClient
from ..logger import get_logger

logger = get_logger(__name__)


def build_dashboard_sheet(
    workbook,
    sheet_name: str,
    department: str,
    kpi_items: List[tuple[str, str]],
    visuals: List[Dict[str, object]],
    nav_items: List[str],
) -> None:
    if sheet_name in workbook.sheetnames:
        ws = workbook[sheet_name]
        workbook.remove(ws)
    ws = workbook.create_sheet(sheet_name, 0)

    # Layout sizing
    ws.column_dimensions["A"].width = 18
    ws.column_dimensions["B"].width = 3
    for col in range(3, 13):
        ws.column_dimensions[get_column_letter(col)].width = 18

    # Colors
    header_fill = PatternFill("solid", fgColor="0F766E")
    nav_fill = PatternFill("solid", fgColor="0F172A")
    card_fill = PatternFill("solid", fgColor="F1F5F9")
    footer_fill = PatternFill("solid", fgColor="0F766E")
    white_font = Font(color="FFFFFF", bold=True)

    # Header
    ws.merge_cells("C1:L2")
    ws["C1"] = f"{department.title()} Dashboard"
    ws["C1"].font = Font(size=18, bold=True, color="FFFFFF")
    ws["C1"].alignment = Alignment(vertical="center", horizontal="left")
    for cell in ws["C1:L2"][0]:
        cell.fill = header_fill
    ws["K2"] = datetime.utcnow().strftime("%Y-%m-%d")
    ws["K2"].font = Font(color="FFFFFF")

    # Left nav
    ws.merge_cells("A1:B2")
    ws["A1"] = "Navigation"
    ws["A1"].font = white_font
    ws["A1"].fill = nav_fill
    ws["A1"].alignment = Alignment(horizontal="center", vertical="center")
    row = 3
    for item in nav_items:
        ws.merge_cells(f"A{row}:B{row}")
        ws[f"A{row}"] = item
        ws[f"A{row}"].font = Font(color="FFFFFF")
        ws[f"A{row}"].fill = nav_fill
        ws[f"A{row}"].alignment = Alignment(horizontal="left", vertical="center")
        if item in workbook.sheetnames:
            ws[f"A{row}"].hyperlink = f"#{item}!A1"
        row += 1

    # KPI cards (2 rows x 3 cols)
    start_row = 3
    start_col = 3
    card_width = 3
    card_height = 2
    max_cards = 6
    border = Border(
        left=Side(style="thin", color="CBD5E1"),
        right=Side(style="thin", color="CBD5E1"),
        top=Side(style="thin", color="CBD5E1"),
        bottom=Side(style="thin", color="CBD5E1"),
    )

    for idx, (label, value) in enumerate(kpi_items[:max_cards]):
        r = start_row + (idx // 3) * (card_height + 1)
        c = start_col + (idx % 3) * (card_width + 1)
        cell_range = f"{get_column_letter(c)}{r}:{get_column_letter(c+card_width-1)}{r+card_height-1}"
        ws.merge_cells(cell_range)
        cell = ws[f"{get_column_letter(c)}{r}"]
        cell.value = f"{label}\n{value}"
        cell.alignment = Alignment(horizontal="left", vertical="center", wrap_text=True)
        cell.font = Font(size=11, bold=True, color="0F172A")
        for row_cells in ws[cell_range]:
            for cell_item in row_cells:
                cell_item.fill = card_fill
                cell_item.border = border

    # Charts area
    chart_row = 9
    chart_col_left = 3
    chart_col_right = 8

    qc = QuickChartClient()
    for idx, visual in enumerate(visuals[:2]):
        image_bytes = _render_quickchart(visual, qc)
        if not image_bytes:
            continue
        chart_col = chart_col_left if idx == 0 else chart_col_right
        anchor = f"{get_column_letter(chart_col)}{chart_row}"
        image_path = Path(f"state/tmp_chart_{sheet_name}_{idx}.png")
        image_path.parent.mkdir(parents=True, exist_ok=True)
        image_path.write_bytes(image_bytes)
        img = XLImage(str(image_path))
        img.width = 440
        img.height = 260
        ws.add_image(img, anchor)

    # Footer
    ws.merge_cells("C20:L21")
    ws["C20"] = "Generated by Autonomous Data Analyst Agent"
    ws["C20"].font = white_font
    ws["C20"].alignment = Alignment(horizontal="left", vertical="center")
    for cell in ws["C20:L21"][0]:
        cell.fill = footer_fill


def _render_quickchart(visual: Dict[str, object], qc: QuickChartClient) -> bytes | None:
    labels = []
    values = []
    for item in visual.get("data", []):
        if not isinstance(item, dict):
            continue
        labels.append(str(item.get(visual.get("x", ""), "")))
        raw = str(item.get(visual.get("y", ""), "0")).replace(",", "")
        try:
            values.append(float(raw))
        except ValueError:
            values.append(0.0)
    if not labels:
        return None
    chart_type = visual.get("type", "bar")
    config = {
        "type": "bar" if chart_type == "donut" else chart_type,
        "data": {"labels": labels, "datasets": [{"data": values}]},
        "options": {"plugins": {"legend": {"display": False}}},
    }
    return qc.render_chart(config, width=800, height=300, background="#F8FAFC")
